name: 问题 | Bug
description: Create a report to help us improve
title: '[Bug]: '

body:
  - type: markdown
    attributes:
      value: |
        重要：请依照模板提交
        Please follow the template to create a new issue

  - type: dropdown
    id: platform
    attributes:
      label: 使用的系統？ || What operating system are you using?
      options:
        - Windows
        - macOS 
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述 | Describe the bug
      description: 请描述你的问题现象 | A clear and concise description of what the bug is.
      placeholder: 请尽量提供截图来描述问题 | If applicable, add screenshots to help explain your problem
      value:
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: 出现问题的QQ | QQ
      description: 请提供可以复现问题的机器人QQ | Please supply a QQ number which can reproduce problem.
      placeholder: 可以留空 | Can be left blank
    validations:
      required: 
